# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 079068b0255d4b983b75f22ba516cff45e6f8855f1a95398416588e91b03576002f42196c87af93e8aa00e1e0f41a117aaccc1cd0a39a88118196e0a418547ae

test:
  secret_key_base: c82369f81c4f5c0fb01235838881141cdad2aa92ad94dab6512c7070a1843bd513cb85d139db3d790e0a97098be57eec0812720d3295ea8dc0d34a123d149add

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
